services:
  # Redis Cache
  ##redis:
  ##  image: redis:7-alpine
  ##  container_name: bite-redis
  ##  ports:
  ##    - "6379:6379"
  ##  volumes:
  ##    - redis_data:/data
  ##  networks:
  ##    - bite-network
  ##  restart: unless-stopped
  ##  healthcheck:
  ##    test: ["CMD", "redis-cli", "ping"]
  ##    interval: 10s
  ##    timeout: 5s
  ##    retries: 5

  # Kong API Gateway (Declarative/DB-less mode)
  kong:
    image: kong:latest
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "8000:8000"   # Kong Proxy HTTP
      - "8443:8443"   # Kong Proxy HTTPS
      - "8001:8001"   # Kong Admin API HTTP
      - "8444:8444"   # Kong Admin API HTTPS
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    networks:
      - bite-network
    depends_on:
      django-app:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Django Application with Gunicorn
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bite-django
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      # Permite todos los hosts IPv4
      ALLOWED_HOSTS: '*'
      DB_NAME: ${DB_NAME:-bite_latency}
      DB_USER: ${DB_USER:-bite_user}
      DB_PASSWORD: ${DB_PASSWORD:-bite_pass}
      # Conecta al host de la EC2 mediante la IP del puente de Docker
      DB_HOST: ${DB_HOST:-172.17.0.1}
      DB_PORT: ${DB_PORT:-5434}
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - static_volume:/app/static
    networks:
      - bite-network
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: /bin/sh -c "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 4 --timeout 120"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bite-network:
    driver: bridge

volumes:
  # redis_data:
  static_volume: